#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: atlassian/default-image:3

pipelines:
  branches:
    develop:
      - step:
          name: Deploy to dev server
          script:
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: ubuntu
              SERVER: 57.180.206.67
              COMMAND: >
                cd ~/deploy/backend && git pull origin develop && cd ~/deploy/backend && sudo docker compose down --remove-orphans && sudo docker compose build --no-cache && sudo docker compose up -d
          services:
          - docker
    master:
      - step:
          name: Deploy to Production server
          script:
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: ubuntu
              SERVER: 57.180.206.67
              COMMAND: >
                cd ~/deploy/backend && git pull origin master && cd ~/deploy/backend && sudo docker compose up --build -d
          services:
          - docker
